#!/usr/bin/env python3
"""
sync_tokens.py — Design Token Synchronization Tool

Reads a design tokens JSON file and generates:
  1. CSS custom properties file
  2. Tailwind configuration (JS module)
  3. TypeScript constants file

Usage:
    python sync_tokens.py tokens.json --output-dir ./generated
    python sync_tokens.py tokens.json --output-dir ./generated --prefix ds
    python sync_tokens.py tokens.json --output-dir ./generated --dark-file dark.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class TokenConfig:
    """Configuration for token generation."""

    input_path: Path
    output_dir: Path
    prefix: str = "ds"
    dark_file: Path | None = None
    css_filename: str = "tokens.css"
    css_dark_filename: str = "tokens-dark.css"
    tailwind_filename: str = "tailwind-tokens.js"
    ts_filename: str = "tokens.ts"


def load_json(path: Path) -> dict[str, Any]:
    """Load and validate a JSON token file."""
    if not path.exists():
        print(f"Error: File not found: {path}", file=sys.stderr)
        sys.exit(1)
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {path}: {e}", file=sys.stderr)
        sys.exit(1)


def flatten_tokens(
    data: dict[str, Any], prefix: str = "", separator: str = "-"
) -> list[tuple[str, str]]:
    """
    Recursively flatten a nested token dictionary into a list of (key, value) tuples.

    Leaf nodes are identified by having a "value" key.
    Example: {"color": {"blue": {"500": {"value": "#3b82f6"}}}}
    Yields: [("color-blue-500", "#3b82f6")]
    """
    results: list[tuple[str, str]] = []
    for key, val in data.items():
        token_key = f"{prefix}{separator}{key}" if prefix else key
        if isinstance(val, dict):
            if "value" in val and not any(
                isinstance(v, dict) for k, v in val.items() if k != "value"
            ):
                # Leaf token node
                results.append((token_key, str(val["value"])))
            else:
                # Nested group — recurse
                nested = {k: v for k, v in val.items() if k != "value"}
                results.extend(flatten_tokens(nested, token_key, separator))
        else:
            # Plain value (no wrapper object)
            results.append((token_key, str(val)))
    return results


def resolve_references(value: str, flat_tokens: dict[str, str], prefix: str) -> str:
    """
    Resolve token references like {color.blue.500} to CSS variable references.
    """
    import re

    def replace_ref(match: re.Match) -> str:
        ref_path = match.group(1).replace(".", "-")
        css_var = f"--{prefix}-{ref_path}"
        return f"var({css_var})"

    return re.sub(r"\{([^}]+)\}", replace_ref, value)


# ---------------------------------------------------------------------------
# CSS Generator
# ---------------------------------------------------------------------------


def generate_css(
    tokens: list[tuple[str, str]],
    prefix: str,
    all_flat: dict[str, str],
) -> str:
    """Generate a CSS file with custom properties."""
    lines: list[str] = []
    lines.append(f"/* Auto-generated by sync_tokens.py — {_timestamp()} */")
    lines.append("/* Do not edit manually. */")
    lines.append("")
    lines.append(":root {")

    current_category = ""
    for key, value in tokens:
        category = key.split("-")[0] if "-" in key else key
        if category != current_category:
            if current_category:
                lines.append("")
            lines.append(f"  /* {category} */")
            current_category = category

        resolved = resolve_references(value, all_flat, prefix)
        lines.append(f"  --{prefix}-{key}: {resolved};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dark_css(
    tokens: list[tuple[str, str]],
    prefix: str,
    all_flat: dict[str, str],
) -> str:
    """Generate a dark-mode CSS override file."""
    lines: list[str] = []
    lines.append(f"/* Auto-generated dark mode tokens — {_timestamp()} */")
    lines.append("/* Do not edit manually. */")
    lines.append("")
    lines.append('[data-theme="dark"],')
    lines.append(".dark {")

    for key, value in tokens:
        resolved = resolve_references(value, all_flat, prefix)
        lines.append(f"  --{prefix}-{key}: {resolved};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tailwind Generator
# ---------------------------------------------------------------------------


def nest_tokens(flat: list[tuple[str, str]], prefix: str) -> dict[str, Any]:
    """
    Convert flat token list into a nested dict suitable for Tailwind config.
    Values become CSS variable references.
    """
    result: dict[str, Any] = {}
    for key, _value in flat:
        parts = key.split("-")
        node = result
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        # Value references the CSS variable so Tailwind picks up theme changes
        node[parts[-1]] = f"var(--{prefix}-{key})"
    return result


def _dict_to_js(d: dict | str, indent: int = 2) -> str:
    """Convert a Python dict to a JavaScript object literal string."""
    if isinstance(d, str):
        return f"'{d}'"

    pad = " " * indent
    inner_pad = " " * (indent + 2)
    items: list[str] = []
    for k, v in d.items():
        # Quote keys that contain special chars like '.'
        key_str = f"'{k}'" if not k.isidentifier() or k[0].isdigit() else k
        if isinstance(v, dict):
            items.append(f"{inner_pad}{key_str}: {_dict_to_js(v, indent + 2)}")
        else:
            items.append(f"{inner_pad}{key_str}: '{v}'")

    joined = ",\n".join(items)
    return f"{{\n{joined}\n{pad}}}"


def generate_tailwind(flat: list[tuple[str, str]], prefix: str) -> str:
    """Generate a Tailwind-compatible JS module exporting token values."""
    nested = nest_tokens(flat, prefix)

    lines: list[str] = []
    lines.append(f"// Auto-generated by sync_tokens.py — {_timestamp()}")
    lines.append("// Do not edit manually.")
    lines.append("")

    # Export each top-level category
    for category, subtree in nested.items():
        var_name = _to_camel(category)
        js_obj = _dict_to_js(subtree) if isinstance(subtree, dict) else f"'{subtree}'"
        lines.append(f"const {var_name} = {js_obj};")
        lines.append("")

    # Module exports
    export_names = [_to_camel(c) for c in nested.keys()]
    lines.append("module.exports = {")
    for name in export_names:
        lines.append(f"  {name},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# TypeScript Generator
# ---------------------------------------------------------------------------


def generate_typescript(flat: list[tuple[str, str]], prefix: str) -> str:
    """Generate a TypeScript constants file with token values as CSS variable references."""
    lines: list[str] = []
    lines.append(f"// Auto-generated by sync_tokens.py — {_timestamp()}")
    lines.append("// Do not edit manually.")
    lines.append("")

    # Group by top-level category
    categories: dict[str, list[tuple[str, str]]] = {}
    for key, value in flat:
        category = key.split("-")[0]
        categories.setdefault(category, []).append((key, value))

    for category, tokens in categories.items():
        type_name = _to_pascal(category) + "Tokens"
        const_name = _to_camel(category) + "Tokens"

        lines.append(f"export const {const_name} = {{")
        for key, _value in tokens:
            # Use the full key minus the category prefix for the object key
            short_key = key[len(category) + 1 :] if key.startswith(category + "-") else key
            ts_key = _quote_if_needed(short_key)
            lines.append(f"  {ts_key}: 'var(--{prefix}-{key})',")
        lines.append("} as const;")
        lines.append("")
        lines.append(
            f"export type {type_name} = keyof typeof {const_name};"
        )
        lines.append("")

    # All-tokens union
    lines.append("/** All available token CSS variable names. */")
    lines.append("export const allTokens = {")
    for key, _value in flat:
        ts_key = _quote_if_needed(key)
        lines.append(f"  {ts_key}: 'var(--{prefix}-{key})',")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type TokenName = keyof typeof allTokens;")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _to_camel(s: str) -> str:
    parts = s.replace("-", "_").split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _to_pascal(s: str) -> str:
    return "".join(p.capitalize() for p in s.replace("-", "_").split("_"))


def _quote_if_needed(s: str) -> str:
    """Quote a key if it is not a valid JS identifier."""
    if not s.isidentifier() or s[0].isdigit() or "-" in s or "." in s:
        return f"'{s}'"
    return s


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def write_file(path: Path, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  Written: {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate CSS, Tailwind, and TypeScript outputs from design tokens JSON."
    )
    parser.add_argument("input", type=Path, help="Path to the design tokens JSON file.")
    parser.add_argument(
        "--output-dir",
        "-o",
        type=Path,
        default=Path("./generated"),
        help="Output directory (default: ./generated).",
    )
    parser.add_argument(
        "--prefix",
        "-p",
        type=str,
        default="ds",
        help="CSS custom property prefix (default: ds).",
    )
    parser.add_argument(
        "--dark-file",
        "-d",
        type=Path,
        default=None,
        help="Optional dark-mode token overrides JSON file.",
    )
    args = parser.parse_args()

    config = TokenConfig(
        input_path=args.input,
        output_dir=args.output_dir,
        prefix=args.prefix,
        dark_file=args.dark_file,
    )

    print(f"Loading tokens from {config.input_path} ...")
    token_data = load_json(config.input_path)
    flat = flatten_tokens(token_data)
    flat_dict = dict(flat)

    print(f"Found {len(flat)} tokens.")

    # Output directories
    css_dir = config.output_dir / "css"
    tailwind_dir = config.output_dir / "tailwind"
    ts_dir = config.output_dir / "ts"
    for d in (css_dir, tailwind_dir, ts_dir):
        ensure_dir(d)

    # Generate CSS
    css_content = generate_css(flat, config.prefix, flat_dict)
    write_file(css_dir / config.css_filename, css_content)

    # Generate dark CSS if provided
    if config.dark_file:
        dark_data = load_json(config.dark_file)
        dark_flat = flatten_tokens(dark_data)
        dark_css = generate_dark_css(dark_flat, config.prefix, flat_dict)
        write_file(css_dir / config.css_dark_filename, dark_css)

    # Generate Tailwind config
    tw_content = generate_tailwind(flat, config.prefix)
    write_file(tailwind_dir / config.tailwind_filename, tw_content)

    # Generate TypeScript
    ts_content = generate_typescript(flat, config.prefix)
    write_file(ts_dir / config.ts_filename, ts_content)

    print(f"\nDone. {len(flat)} tokens synced to {config.output_dir}")


if __name__ == "__main__":
    main()
