#!/usr/bin/env python3
"""
La-Z-Boy Brand Token Generator
================================
Outputs La-Z-Boy brand design tokens in multiple formats.

Usage:
    python generate_tokens.py css          # CSS custom properties (:root)
    python generate_tokens.py json         # Style Dictionary / Figma Tokens format
    python generate_tokens.py tailwind     # Tailwind config theme extension
    python generate_tokens.py all          # All formats, saved to files

Output files (when using 'all'):
    brand-tokens.css
    brand-tokens.json
    brand-tokens.tailwind.js
"""

import sys
import json

# ── Token definitions ────────────────────────────────────────────────────────
TOKENS = {
    "color": {
        "primary":     {"value": "#1B3A6B", "description": "Comfort Blue — logo, headings, hero bg"},
        "accent":      {"value": "#C0392B", "description": "Burnt Vermilion — CTAs, accents, dividers"},
        "green":       {"value": "#8FAF8A", "description": "Soft Celadon — secondary accent, decorative only"},
        "bg":          {"value": "#FAF8F5", "description": "Warm White — page and slide backgrounds"},
        "text":        {"value": "#2C2C2C", "description": "Charcoal — body text, captions"},
        "text-light":  {"value": "rgba(44,44,44,0.6)", "description": "Charcoal 60% — secondary text"},
        "white":       {"value": "#FFFFFF", "description": "White — reversed text on dark backgrounds"},
        "black":       {"value": "#000000", "description": "Black — one-color logo, fine print"},
        "legacy-red":  {"value": "#CC0000", "description": "La-Z-Boy Red — legacy materials only"},
    },
    "font": {
        "stack":       {"value": "'Helvetica Neue', Helvetica, Arial, sans-serif", "description": "Primary font stack"},
        "size-h1":     {"value": "clamp(32px, 5vw, 48px)", "description": "H1 display"},
        "size-h2":     {"value": "clamp(24px, 4vw, 32px)", "description": "H2 heading"},
        "size-h3":     {"value": "20px",   "description": "H3 subheading"},
        "size-body":   {"value": "15px",   "description": "Body copy"},
        "size-caption":{"value": "12px",   "description": "Caption / fine print"},
        "weight-bold": {"value": "700",    "description": "Bold — headings"},
        "weight-semi": {"value": "600",    "description": "Semi-Bold — subheadings, UI labels"},
        "weight-body": {"value": "400",    "description": "Regular — body text"},
    },
    "radius": {
        "sm":  {"value": "4px",  "description": "Small radius — inputs, tags"},
        "md":  {"value": "8px",  "description": "Medium radius — cards, buttons"},
        "lg":  {"value": "16px", "description": "Large radius — panels, modals"},
        "full":{"value": "9999px","description":"Full pill — badges, chips"},
    },
    "spacing": {
        "xs":  {"value": "4px"},
        "sm":  {"value": "8px"},
        "md":  {"value": "16px"},
        "lg":  {"value": "24px"},
        "xl":  {"value": "32px"},
        "2xl": {"value": "48px"},
        "3xl": {"value": "64px"},
    }
}

# ── Formatters ───────────────────────────────────────────────────────────────
def to_css():
    lines = ["/* La-Z-Boy Brand Tokens — generated by generate_tokens.py */", ":root {"]
    for category, tokens in TOKENS.items():
        lines.append(f"\n  /* {category.upper()} */")
        for name, data in tokens.items():
            comment = f" /* {data['description']} */" if data.get('description') else ""
            lines.append(f"  --{category}-{name}: {data['value']};{comment}")
    lines.append("}")
    return "\n".join(lines)

def to_json():
    output = {}
    for category, tokens in TOKENS.items():
        output[category] = {}
        for name, data in tokens.items():
            output[category][name] = {
                "value": data["value"],
                "type": category,
            }
            if data.get("description"):
                output[category][name]["description"] = data["description"]
    return json.dumps(output, indent=2)

def to_tailwind():
    colors = {k: v["value"] for k, v in TOKENS["color"].items()}
    radii = {k: v["value"] for k, v in TOKENS["radius"].items()}
    spacing = {k: v["value"] for k, v in TOKENS["spacing"].items()}
    font_sizes = {
        k.replace("size-", ""): v["value"]
        for k, v in TOKENS["font"].items()
        if k.startswith("size-")
    }
    lines = [
        "// La-Z-Boy Brand Tokens — Tailwind config extension",
        "// Usage: merge this into your tailwind.config.js theme.extend",
        "",
        "module.exports = {",
        "  theme: {",
        "    extend: {",
        "      colors: {",
        "        'lazboy': {"
    ]
    for k, v in colors.items():
        lines.append(f"          '{k}': '{v}',")
    lines += [
        "        },",
        "      },",
        "      borderRadius: {"
    ]
    for k, v in radii.items():
        lines.append(f"        'lzb-{k}': '{v}',")
    lines += [
        "      },",
        "      fontSize: {"
    ]
    for k, v in font_sizes.items():
        lines.append(f"        'lzb-{k}': '{v}',")
    lines += [
        "      },",
        "    },",
        "  },",
        "};",
    ]
    return "\n".join(lines)

# ── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    fmt = sys.argv[1] if len(sys.argv) > 1 else "all"

    if fmt == "css":
        print(to_css())

    elif fmt == "json":
        print(to_json())

    elif fmt == "tailwind":
        print(to_tailwind())

    elif fmt == "all":
        with open("brand-tokens.css", "w") as f:
            f.write(to_css())
        print("✅ Written: brand-tokens.css")

        with open("brand-tokens.json", "w") as f:
            f.write(to_json())
        print("✅ Written: brand-tokens.json")

        with open("brand-tokens.tailwind.js", "w") as f:
            f.write(to_tailwind())
        print("✅ Written: brand-tokens.tailwind.js")

    else:
        print(__doc__)
        sys.exit(1)
